apiVersion: apps/v1
kind: Deployment
metadata:
  name: gophie
  namespace: gophie
  labels:
    app: gophie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gophie
  template:
    metadata:
      labels:
        app: gophie
    spec:
      containers:
      - name: gophie
        image: gcr.io/khidom/gophie:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: gophie
  namespace: gophie
spec:
  type: ClusterIP
  selector:
    app: gophie
  ports:
  - port: 80
    targetPort: 3000

